apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2023-08-09T07:11:34Z"
  generation: 1
  labels:
    app: petclinic
  name: petclinic
  namespace: default
  resourceVersion: "664609"
  uid: 1a3b1072-7af5-4aef-9669-9c998389f3c5
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: petclinic
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: petclinic
    spec:
      containers:
      - image: vdhar/gradle-petclinic:1.13
        imagePullPolicy: IfNotPresent
        name: gradle-petclinic
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
