apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: petclinic
  name: petclinic-app
  labels:
    app: petclinic-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petclinic-app
  template:
    metadata:
      labels:
        app: petclinic-app
    spec:
      containers:
      - name: petclinic-app
        image: vdhar/gradle-petclinic:${IMG_VER}.${BUILD_NUMBER}
        ports:
        - containerPort: 8080
